version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 60s
      retries: 5
      start_period: 80s

  django_app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    volumes:
      - static_value:/django_app/static/
      - media_value:/django_app/media/
      - ./:/django_app
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx_default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - django_app

volumes:
  static_value:
  media_value:
  db_value: