# Generated by Django 3.2.14 on 2023-02-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_on'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.RenameField(
            model_name='itemsinorder',
            old_name='items',
            new_name='item',
        ),
    ]
