# Generated by Django 3.2.14 on 2023-02-26 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230224_1808'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='stripe_payment_intent',
            new_name='stripe_session_id',
        ),
    ]
